spring:
  application:
    name: Car Rental System

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/car-rental-system?useSSL=false
    username: root
    password: 123456

  docker:
    compose:
      enabled: false
      file: docker-compose.yaml

custom:
  jwt:
    secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A7
    access-token-expired: 30
    refresh-token-expired: 60