spring:
  application:
    name: Car Rental System

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car-rental-system?allowPublicKeyRetrieval=true
    username: root
    password: 123456
  
  jpa:
    hibernate:
      ddl-auto: update
  #  sql:
  #    init:
  #      mode: always
  #      schema-locations: classpath:schema.sql
  #      data-locations: classpath:data.sql
  
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml

  springdoc:
    swagger-ui:
      enabled: true

custom:
  jwt:
    secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A7
    access-token-expired: 30
    refresh-token-expired: 60
