spring:
  application:
    name: Car Rental System

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  springdoc:
    swagger-ui:
      enabled: true

  docker:
    compose:
      enabled: false
      file: docker-compose.yaml

custom:
  jwt:
    secret-key: ${JWT_SECRETKEY}
    access-token-expired: 30
    refresh-token-expired: 60
